version: '3.7'
services:
  wordpress_1:
    image: wordpress
    container_name: "wordpress_1"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - cangrownet
    depends_on:
      - db

  wordpress_2:
    image: wordpress
    container_name: "wordpress_2"
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - cangrownet
    depends_on:
      - wordpress_1

  db:
    image: mariadb
    container_name: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - cangrownet

  load_balancer:
    image: nginx
    container_name: "load_balancer"
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - cangrownet
    depends_on:
      - wordpress_2

networks:
  cangrownet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 69.85.0.0/28
