services:
  wordpress_1:
    image: wordpress
    container_name: "wordpress_1"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: master_db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - cangrownet
    depends_on:
      - replica_db

  wordpress_2:
    image: wordpress
    container_name: "wordpress_2"
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: master_db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - cangrownet
    depends_on:
      - wordpress_1

  master_db:
    image: mariadb:latest
    container_name: "masterdb"
    restart: always
    volumes:
      - ./masterdb/mastercnf:/etc/mysql/conf.d:z
      - ./masterdb/masterinit:/docker-entrypoint-initdb.d:z
      - ./masterdb/logs:/var/lib/mysql
    working_dir: /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: root
      MYSQL_INITDB_SKIP_TZINFO: "Y"
    networks:
      - cangrownet
  
  replica_db:
    image: mariadb:latest
    container_name: "replicadb"
    restart: always  
    volumes:
      - ./replicadb/replicacnf:/etc/mysql/conf.d:z
      - ./replicadb/replicainit:/docker-entrypoint-initdb.d:z
      - ./replicadb/logs:/var/lib/mysql
    working_dir: /var/lib/mysql
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: root
      MYSQL_INITDB_SKIP_TZINFO: "Y"
    networks:
      - cangrownet
    depends_on:
      - master_db

  load_balancer:
    image: nginx
    container_name: "load_balancer"
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - cangrownet
    depends_on:
      - wordpress_2

networks:
  cangrownet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 69.85.0.0/28
